"""Concepts, metrics, cohorts, data, capabilities, evidence, conflicts."""
from __future__ import annotations

from pack_records import (
    CODE_SHA,
    PUBLICATION,
    RFM_THRESHOLD_VERSION,
    TEXTBOOK,
    _base,
)

HUMAN_DECISION = "human_curated_from_confirmed_decisions"
HUMAN_OCR = "human_curated_from_textbook_ocr"
HUMAN_CODE = "human_curated_from_source_snapshot"
HUMAN_DESIGN = "human_curated_from_design_docs"


CONCEPTS = [
    {"id": "concept.aus", "name": "客单价 / 人均消费金额", "aliases": ["AUS", "客单价", "人均消费金额"]},
    {"id": "concept.aov", "name": "每单金额", "aliases": ["AOV", "平均订单金额"]},
    {"id": "concept.valid_purchase", "name": "有效购买", "aliases": ["有效订单", "有效人数"]},
    {"id": "concept.gsv", "name": "GSV 净销售", "aliases": ["GSV"]},
    {"id": "concept.gmv", "name": "GMV 成交总额", "aliases": ["GMV"]},
    {"id": "concept.member_premium", "name": "会员溢价", "aliases": ["会员溢价率", "Member premium"]},
    {"id": "concept.new_old", "name": "新老客", "aliases": ["NTF", "Existing Customer"]},
    {"id": "concept.frequency", "name": "人均购买次数", "aliases": ["Frequency"]},
    {"id": "concept.ipt", "name": "客单件 / 件数", "aliases": ["IPT", "人均购买件数", "每单件数"]},
    {"id": "concept.aup", "name": "件单价", "aliases": ["AUP"]},
    {"id": "concept.retention", "name": "老客回购", "aliases": ["Retention rate"]},
    {"id": "concept.new_repeat", "name": "新客复购", "aliases": ["New Repeat rate"]},
    {"id": "concept.basket", "name": "商品连带", "aliases": ["商品连带率"]},
    {"id": "concept.product_acquisition", "name": "商品招新", "aliases": ["商品招新率"]},
    {"id": "concept.product_penetration", "name": "商品渗透", "aliases": ["新客渗透率", "老客渗透率"]},
    {"id": "concept.product_repurchase", "name": "商品回购", "aliases": ["Commodity Repurchase Rate"]},
    {"id": "concept.member_recruitment", "name": "新会员招募", "aliases": ["新会员招募数"]},
    {"id": "concept.member_share", "name": "会员成交占比", "aliases": ["会员渗透"]},
    {"id": "concept.binding_rate", "name": "绑卡率 / 入会率", "aliases": ["Binding Rate"]},
    {"id": "concept.new_member_conversion", "name": "新会员转化", "aliases": ["New member Conversion Rate"]},
    {"id": "concept.old_member_retention", "name": "老会员回购", "aliases": ["老会员回购率"]},
    {"id": "concept.old_customer_join", "name": "老客入会", "aliases": ["老客入会率"]},
    {"id": "concept.sample_window", "name": "派样观察窗口", "aliases": ["派样 ROI", "派样复购"]},
    {"id": "concept.ltv", "name": "LTV / 新客累计净消费", "aliases": ["LTV", "cohort 后续收入"]},
    {"id": "concept.uv", "name": "访客与入会率分母", "aliases": ["UV", "日UV累计"]},
    {"id": "concept.yoy", "name": "同比日历", "aliases": ["YOY"]},
    {"id": "concept.rfm", "name": "RFM 分层", "aliases": ["RFM"]},
    {"id": "concept.refund_view", "name": "退款视图", "aliases": ["原订单期净额", "退款发生期"]},
    {"id": "concept.membership_at_purchase", "name": "成交时会员身份", "aliases": ["MEMBER", "NON_MEMBER", "UNKNOWN"]},
]
for c in CONCEPTS:
    c.update(_base(type="BusinessConcept", domain="crm", formula=None, note="概念不直接存唯一公式。"))


# Public edition: citation IDs/pages remain, but private source text is omitted.
TEXTBOOK_EXCERPTS = [
    {
        "id": "tb.01.new_share",
        "slide": 160,
        "ordinal": 1,
        "name": "新客成交占比",
        "ocr_excerpt": None,
        "concept_id": "concept.new_old",
        "ambiguity": None,
    },
    {
        "id": "tb.02.old_share",
        "slide": 160,
        "ordinal": 2,
        "name": "老客成交占比",
        "ocr_excerpt": None,
        "concept_id": "concept.new_old",
        "ambiguity": None,
    },
    {
        "id": "tb.03.aus",
        "slide": 160,
        "ordinal": 3,
        "name": "客单价|人均消费金额",
        "ocr_excerpt": None,
        "concept_id": "concept.aus",
        "ambiguity": None,
    },
    {
        "id": "tb.04.ipt",
        "slide": 160,
        "ordinal": 4,
        "name": "客单件|人均购买件数",
        "ocr_excerpt": None,
        "concept_id": "concept.ipt",
        "ambiguity": "名词解释按交易/订单，公式分母是购买人数。不根据 OCR 猜测统一。",
    },
    {
        "id": "tb.05.aup",
        "slide": 160,
        "ordinal": 5,
        "name": "件单价",
        "ocr_excerpt": None,
        "concept_id": "concept.aup",
        "ambiguity": None,
    },
    {
        "id": "tb.06.frequency",
        "slide": 160,
        "ordinal": 6,
        "name": "人均购买次数",
        "ocr_excerpt": None,
        "concept_id": "concept.frequency",
        "ambiguity": "购买总次数是否去重订单未在教材页写明。",
    },
    {
        "id": "tb.07.retention",
        "slide": 160,
        "ordinal": 7,
        "name": "老客回购率",
        "ocr_excerpt": None,
        "concept_id": "concept.retention",
        "ambiguity": None,
    },
    {
        "id": "tb.08.new_repeat",
        "slide": 160,
        "ordinal": 8,
        "name": "新客复购率",
        "ocr_excerpt": None,
        "concept_id": "concept.new_repeat",
        "ambiguity": "“当期新客期内复购”与“首购后 N 日复购”教材未分列。",
    },
    {
        "id": "tb.09.basket",
        "slide": 160,
        "ordinal": 9,
        "name": "商品连带率",
        "ocr_excerpt": None,
        "concept_id": "concept.basket",
        "ambiguity": "描述同单，公式按人数。",
    },
    {
        "id": "tb.10.product_acq",
        "slide": 160,
        "ordinal": 10,
        "name": "商品招新率",
        "ocr_excerpt": None,
        "concept_id": "concept.product_acquisition",
        "ambiguity": "“销售占比”未锁定人数或金额。",
    },
    {
        "id": "tb.11.new_pen",
        "slide": 161,
        "ordinal": 11,
        "name": "商品新客渗透率",
        "ocr_excerpt": None,
        "concept_id": "concept.product_penetration",
        "ambiguity": None,
    },
    {
        "id": "tb.12.old_pen",
        "slide": 161,
        "ordinal": 12,
        "name": "商品老客渗透率",
        "ocr_excerpt": None,
        "concept_id": "concept.product_penetration",
        "ambiguity": None,
    },
    {
        "id": "tb.13.product_repurchase",
        "slide": 161,
        "ordinal": 13,
        "name": "商品回购率",
        "ocr_excerpt": None,
        "concept_id": "concept.product_repurchase",
        "ambiguity": "简写缺少历史集合交集，分子可能计入历史未买过 A 的人。",
    },
    {
        "id": "tb.14.recruit",
        "slide": 161,
        "ordinal": 14,
        "name": "新会员招募数",
        "ocr_excerpt": None,
        "concept_id": "concept.member_recruitment",
        "ambiguity": None,
    },
    {
        "id": "tb.15.member_share",
        "slide": 161,
        "ordinal": 15,
        "name": "会员成交占比/会员成交渗透",
        "ocr_excerpt": None,
        "concept_id": "concept.member_share",
        "ambiguity": None,
    },
    {
        "id": "tb.16.premium",
        "slide": 161,
        "ordinal": 16,
        "name": "会员溢价率",
        "ocr_excerpt": None,
        "concept_id": "concept.member_premium",
        "ambiguity": None,
    },
    {
        "id": "tb.17.binding",
        "slide": 161,
        "ordinal": 17,
        "name": "会员绑卡率",
        "ocr_excerpt": None,
        "concept_id": "concept.binding_rate",
        "ambiguity": "绑卡与入会、访问去重粒度未在该页展开。",
    },
    {
        "id": "tb.18.new_member_conv",
        "slide": 161,
        "ordinal": 18,
        "name": "新会员转化率",
        "ocr_excerpt": None,
        "concept_id": "concept.new_member_conversion",
        "ambiguity": "观察期/成熟度未写。",
    },
    {
        "id": "tb.19.old_member_ret",
        "slide": 161,
        "ordinal": 19,
        "name": "老会员回购率",
        "ocr_excerpt": None,
        "concept_id": "concept.old_member_retention",
        "ambiguity": "存量是否含未购会员未写清。",
    },
    {
        "id": "tb.20.old_join",
        "slide": 161,
        "ordinal": 20,
        "name": "老客入会率",
        "ocr_excerpt": None,
        "concept_id": "concept.old_customer_join",
        "ambiguity": None,
    },
    {
        "id": "tb.rfm.plan",
        "slide": 25,
        "ordinal": None,
        "name": "老客 RFM 预估",
        "ocr_excerpt": None,
        "concept_id": "concept.rfm",
        "ambiguity": "教材运营预估式，不是已验证计算合同。",
    },
    {
        "id": "tb.quadrant.gmv",
        "slide": 34,
        "ordinal": None,
        "name": "会员黄金四象限拆解",
        "ocr_excerpt": None,
        "concept_id": "concept.member_share",
        "ambiguity": "OCR 数字和人群上标可能识别错误；不据此改决议。",
    },
]
for t in TEXTBOOK_EXCERPTS:
    t.update(
        _base(
            type="TextbookExcerpt",
            layer="textbook",
            document_id="doc.textbook.cst-ocr-2026-09-20",
            original_document_id="doc.textbook.cst-pptx",
            ocr_status=TEXTBOOK["ocr_status"],
            definition_review_status="textbook_ocr_uncorrected"
            if not t.get("ambiguity")
            else "textbook_internal_ambiguity",
            implementation_status="not_implemented",
            content_omitted=True,
            note="私有教材索引，原文未公开分发。不是正式定义，也不是代码已修复声明。",
        )
    )


def _metric(**kwargs):
    rec = _base(type="MetricDefinition")
    rec.update(kwargs)
    rec.setdefault("verified_implementation", False)
    rec.setdefault("contains_real_data", False)
    rec.setdefault("publication_status", PUBLICATION)
    return rec


TARGET_METRICS = [
    _metric(
        id="metric.aus:target-v1",
        concept_id="concept.aus",
        layer="target_definition",
        name="客单价 AUS",
        formula="same_scope_net_amount / distinct_valid_buyers",
        unit="money_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D001", "D003", "D006", "D018"],
        textbook_refs=["tb.03.aus"],
        findings=["M01"],
        numerator="metric.gsv_net:target-v1",
        denominator="cohort.valid_buyers:target-v1",
        requires_data=["data.order_amount", "data.buyer_identity", "data.refund_events"],
        planned_capabilities=["capability.sales_window_summary"],
        note="分母为零时不能写成平均消费为0。",
    ),
    _metric(
        id="metric.aov:target-v1",
        concept_id="concept.aov",
        layer="target_definition",
        name="每单金额 AOV",
        formula="same_scope_net_amount / distinct_valid_orders",
        unit="money_per_order",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D001", "D003", "D006"],
        textbook_refs=["tb.03.aus"],
        findings=["M01"],
        numerator="metric.gsv_net:target-v1",
        denominator="cohort.valid_orders:target-v1",
        requires_data=["data.order_amount", "data.order_id", "data.refund_events"],
        planned_capabilities=["capability.sales_window_summary"],
        note="与 AUS 单列，不得静默改写旧 avg_order_value 字段含义。",
    ),
    _metric(
        id="metric.gsv_net:target-v1",
        concept_id="concept.gsv",
        layer="target_definition",
        name="GSV 净额",
        formula="gross_paid - succeeded_refunds_as_of_A; if amount_already_net then do_not_subtract_again",
        unit="money",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D003", "D005", "D006", "D013"],
        textbook_refs=[],
        findings=["M03", "M04", "M05", "M29"],
        requires_data=["data.order_amount", "data.refund_events"],
        planned_capabilities=["capability.sales_window_summary"],
        note="100退30计70。原金额已净额时禁止再扣。D019 未核验前不得宣称真实出数。",
    ),
    _metric(
        id="metric.member_premium:target-v1",
        concept_id="concept.member_premium",
        layer="target_definition",
        name="会员溢价倍数",
        formula="member_aus / non_member_aus",
        unit="multiple",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D001", "D002", "D014", "D017", "D018"],
        textbook_refs=["tb.16.premium"],
        findings=["M02"],
        numerator="metric.member_aus:target-v1",
        denominator="metric.non_member_aus:target-v1",
        requires_data=["data.membership_at_purchase", "data.order_amount", "data.buyer_identity"],
        planned_capabilities=["capability.sales_window_summary"],
        note="1.2 表示 1.2 倍，不是高 120%。高 20% 是 (1.2-1)×100%，不得装入同一无单位字段。",
    ),
    _metric(
        id="metric.member_aus:target-v1",
        concept_id="concept.aus",
        layer="target_definition",
        name="会员 AUS",
        formula="member_net_amount / distinct_member_buyers_at_purchase",
        unit="money_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D001", "D002", "D014", "D018"],
        textbook_refs=["tb.16.premium"],
        findings=["M02", "M22"],
        requires_data=["data.membership_at_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
        note="期内入会者可先后属于会员与非会员两组，两组人数不能直接相加当全店去重人数。",
    ),
    _metric(
        id="metric.non_member_aus:target-v1",
        concept_id="concept.aus",
        layer="target_definition",
        name="非会员 AUS",
        formula="non_member_net_amount / distinct_non_member_buyers_at_purchase",
        unit="money_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D001", "D002", "D014", "D018"],
        textbook_refs=["tb.16.premium"],
        findings=["M02", "M22"],
        requires_data=["data.membership_at_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.new_buyer_share:target-v1",
        concept_id="concept.new_old",
        layer="target_definition",
        name="新客购买人数占比",
        formula="new_buyers / all_identified_buyers_same_scope",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D017", "D018", "D020", "D021"],
        textbook_refs=["tb.01.new_share"],
        findings=["M06", "M07", "M08", "M09", "M30"],
        requires_data=["data.first_valid_purchase", "data.refund_events"],
        planned_capabilities=["capability.sales_window_summary"],
        note="人数占比与金额占比分列。未知历史单列，不能填老客。",
    ),
    _metric(
        id="metric.new_amount_share:target-v1",
        concept_id="concept.new_old",
        layer="target_definition",
        name="新客金额占比",
        formula="new_net_amount / identified_net_amount_same_scope",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D017", "D018", "D020"],
        textbook_refs=["tb.01.new_share"],
        findings=["M09"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
        note="新+老+未知必须与同口径总额闭合。",
    ),
    _metric(
        id="metric.old_buyer_share:target-v1",
        concept_id="concept.new_old",
        layer="target_definition",
        name="老客购买人数占比",
        formula="old_buyers / all_identified_buyers_same_scope",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D018", "D020", "D021"],
        textbook_refs=["tb.02.old_share"],
        findings=["M06", "M08"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.old_repurchase_rate:target-v1",
        concept_id="concept.retention",
        layer="target_definition",
        name="期初老客回购率",
        formula="buyers_from_opening_old_stock_in_window / opening_old_stock",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D006", "D010", "D018", "D020"],
        textbook_refs=["tb.07.retention"],
        findings=["M06", "M17", "M30"],
        uses_cohorts=["cohort.opening_storewide_old:target-v1"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=["capability.existing_customer_repurchase"],
        note="分母是期初存量，不是当期购买老客。",
    ),
    _metric(
        id="metric.frequency:target-v1",
        concept_id="concept.frequency",
        layer="target_definition",
        name="人均购买次数",
        formula="distinct_valid_orders / distinct_valid_buyers",
        unit="orders_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D007"],
        textbook_refs=["tb.06.frequency"],
        findings=["M13"],
        requires_data=["data.order_id", "data.buyer_identity"],
        planned_capabilities=["capability.sales_window_summary"],
        note="同一订单多行只算一次。购买日次数另命名。",
    ),
    _metric(
        id="metric.items_per_buyer:target-v1",
        concept_id="concept.ipt",
        layer="target_definition",
        name="人均件数",
        formula="in_scope_item_quantity / distinct_valid_buyers",
        unit="items_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D007"],
        textbook_refs=["tb.04.ipt"],
        findings=["M14"],
        requires_data=["data.quantity"],
        planned_capabilities=[],
        note="与每单件数分列。无退件数量时不猜净件数。",
    ),
    _metric(
        id="metric.ipt:target-v1",
        concept_id="concept.ipt",
        layer="target_definition",
        name="每单件数 IPT",
        formula="in_scope_item_quantity / distinct_valid_orders",
        unit="items_per_order",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D007"],
        textbook_refs=["tb.04.ipt"],
        findings=["M14"],
        requires_data=["data.quantity"],
        planned_capabilities=[],
    ),
    _metric(
        id="metric.aup:target-v1",
        concept_id="concept.aup",
        layer="target_definition",
        name="件单价 AUP",
        formula="same_scope_net_amount / in_scope_item_quantity",
        unit="money_per_item",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D007", "D003"],
        textbook_refs=["tb.05.aup"],
        findings=["M14", "M29"],
        requires_data=["data.quantity", "data.order_amount"],
        planned_capabilities=[],
        note="部分退款不等同退件。",
    ),
    _metric(
        id="metric.basket_people:target-v1",
        concept_id="concept.basket",
        layer="target_definition",
        name="人数连带率",
        formula="people_buying_A_and_other_sku_in_same_order / people_buying_A",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008"],
        textbook_refs=["tb.09.basket"],
        findings=["M15"],
        requires_data=["data.product_hierarchy"],
        planned_capabilities=[],
        note="与订单连带、购物篮 confidence 分名。",
    ),
    _metric(
        id="metric.basket_orders:target-v1",
        concept_id="concept.basket",
        layer="target_definition",
        name="订单连带率",
        formula="orders_with_A_and_other_sku / orders_with_A",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008"],
        textbook_refs=["tb.09.basket"],
        findings=["M15"],
        requires_data=["data.product_hierarchy"],
        planned_capabilities=[],
    ),
    _metric(
        id="metric.product_new_people_share:target-v1",
        concept_id="concept.product_acquisition",
        layer="target_definition",
        name="商品招新人数占比",
        formula="new_buyers_of_A / buyers_of_A",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008", "D020"],
        textbook_refs=["tb.10.product_acq"],
        findings=["M16"],
        requires_data=["data.first_valid_purchase", "data.product_hierarchy"],
        planned_capabilities=[],
    ),
    _metric(
        id="metric.product_new_amount_share:target-v1",
        concept_id="concept.product_acquisition",
        layer="target_definition",
        name="商品新客金额占比",
        formula="new_net_amount_of_A / net_amount_of_A",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008", "D013", "D020"],
        textbook_refs=["tb.10.product_acq"],
        findings=["M16", "M10"],
        requires_data=["data.refund_lines"],
        planned_capabilities=[],
        note="无退款明细时受影响商品净额不可用。",
    ),
    _metric(
        id="metric.product_new_penetration:target-v1",
        concept_id="concept.product_penetration",
        layer="target_definition",
        name="商品新客渗透率",
        formula="new_buyers_of_A / storewide_new_buyers_same_definition",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008", "D020"],
        textbook_refs=["tb.11.new_pen"],
        findings=["M16", "M27"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=[],
    ),
    _metric(
        id="metric.product_old_penetration:target-v1",
        concept_id="concept.product_penetration",
        layer="target_definition",
        name="商品老客渗透率",
        formula="old_buyers_of_A / storewide_old_buyers_same_definition",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008", "D020"],
        textbook_refs=["tb.12.old_pen"],
        findings=["M16", "M27"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=[],
        note="多品类比例不能相加当 100%。",
    ),
    _metric(
        id="metric.member_people_share:target-v1",
        concept_id="concept.member_share",
        layer="target_definition",
        name="会员购买人数占比",
        formula="member_buyers_at_purchase / all_identified_buyers_same_scope",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D014", "D017", "D018"],
        textbook_refs=["tb.15.member_share"],
        findings=["M02", "M22"],
        requires_data=["data.membership_at_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.member_amount_share:target-v1",
        concept_id="concept.member_share",
        layer="target_definition",
        name="会员金额占比",
        formula="member_net_amount / same_scope_total",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D014", "D017", "D018"],
        textbook_refs=["tb.15.member_share"],
        findings=["M02", "M09"],
        requires_data=["data.membership_at_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.new_repeat_in_window:target-v1",
        concept_id="concept.new_repeat",
        layer="target_definition",
        name="当期新客期内复购率",
        formula="window_new_buyers_with_2plus_valid_orders / window_new_buyers",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D006", "D007", "D010"],
        textbook_refs=["tb.08.new_repeat"],
        findings=["M19"],
        requires_data=["data.first_valid_purchase", "data.order_id"],
        planned_capabilities=[],
        note="与“首购后 N 日复购”分别定义；后者尚未单列合同，保持未知/未实现。",
    ),
    _metric(
        id="metric.old_amount_share:target-v1",
        concept_id="concept.new_old",
        layer="target_definition",
        name="老客金额占比",
        formula="old_net_amount / same_scope_total",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D004", "D017", "D018", "D020"],
        textbook_refs=["tb.02.old_share"],
        findings=["M09"],
        requires_data=["data.first_valid_purchase"],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.product_repurchase:target-v1",
        concept_id="concept.product_repurchase",
        layer="target_definition",
        name="商品历史集合回购率",
        formula="historical_buyers_of_A_who_buy_A_again / historical_buyers_of_A",
        unit="raw_ratio_0_1",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D008"],
        textbook_refs=["tb.13.product_repurchase"],
        findings=["M17"],
        uses_cohorts=["cohort.historical_buyers_of_product:target-v1"],
        requires_data=["data.product_hierarchy", "data.first_valid_purchase"],
        planned_capabilities=[],
        note="分子必须是历史集合子集。",
    ),
    _metric(
        id="metric.sample_repeat_revenue:target-v1",
        concept_id="concept.sample_window",
        layer="target_definition",
        name="派样后复购收入表现（对外仍称派样 ROI）",
        formula="mature_sample_cohort_followup_net_amount; name retained as 派样 ROI with explicit non-profit caveat",
        unit="money",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D009", "D010", "D011", "D022"],
        textbook_refs=[],
        findings=["M18", "M19", "M20", "M21"],
        uses_cohorts=["cohort.first_sample_in_period:target-v1", "cohort.mature_sample:target-v1"],
        requires_data=["data.sample_identification", "data.pay_time"],
        planned_capabilities=["capability.sample_followup"],
        note="当前只是复购收入表现，不是利润 ROI 或因果增量。",
    ),
    _metric(
        id="metric.ltv_new_customer_n_day:target-v1",
        concept_id="concept.ltv",
        layer="target_definition",
        name="全店新客 N 日累计净消费",
        formula="net_spend_from_first_valid_pay_including_first_order_over_N_natural_days_storewide",
        unit="money_per_person",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D012", "D010", "D021"],
        textbook_refs=[],
        findings=["M24"],
        requires_data=["data.first_valid_purchase", "data.refund_events"],
        planned_capabilities=[],
        note="含首单、全店后续购买、区分成熟度。旧指定日次日起收入单列。",
    ),
    _metric(
        id="metric.yoy_calendar:target-v1",
        concept_id="concept.yoy",
        layer="target_definition",
        name="去年同日同比区间",
        formula="same_calendar_date_last_year; Feb29->Feb28; display actual range",
        unit="date_range",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D016"],
        textbook_refs=[],
        findings=["M25"],
        requires_data=[],
        planned_capabilities=["capability.sales_window_summary"],
    ),
    _metric(
        id="metric.daily_uv_sum:target-v1",
        concept_id="concept.uv",
        layer="target_definition",
        name="日 UV 累计口径",
        formula="sum(daily_visitors); not period-unique UV",
        unit="count",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D015"],
        textbook_refs=["tb.17.binding"],
        findings=["M23"],
        requires_data=["data.daily_visitors"],
        planned_capabilities=[],
        note="周期去重转化另列；数据不具备时说明。",
    ),
    _metric(
        id="metric.rfm_thresholds:target-v1",
        concept_id="concept.rfm",
        layer="target_definition",
        name="RFM 现有阈值版本",
        formula="keep current project thresholds with actual-day labels; do not swap in textbook example cuts",
        unit="threshold_table",
        definition_review_status="principles_confirmed_mapping_pending",
        implementation_status="not_implemented",
        decision_ids=["D016"],
        textbook_refs=["tb.rfm.plan"],
        findings=["M26"],
        requires_data=[],
        planned_capabilities=[],
        rfm_threshold_version=RFM_THRESHOLD_VERSION,
        note="R 桶“近1个月”实际为 30 天，名称须标实际天数。",
    ),
]


CODE_SNAPSHOT_METRICS = [
    _metric(
        id="metric.aus:code-overview-line-avg",
        concept_id="concept.aus",
        layer="code_snapshot",
        name="旧概览 avg_order_value 明细行均",
        formula="AVG(actual_amount) over order lines",
        unit="money_per_line",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D001"],
        textbook_refs=["tb.03.aus"],
        findings=["M01"],
        code_path="backend/services/metrics/overview.py",
        code_sha256=CODE_SHA["backend/services/metrics/overview.py"],
        anchors=["_query_period", "AVG(actual_amount) as avg_order_value"],
        lines=["40", "194"],
        note="不得称为已修复的客单价。保留为技术诊断值。",
    ),
    _metric(
        id="metric.aus:code-category-users",
        concept_id="concept.aus",
        layer="code_snapshot",
        name="品类概览按人数的均额基础",
        formula="total_gsv / COUNT(DISTINCT user_id)",
        unit="money_per_person",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D001"],
        findings=["M01"],
        code_path="backend/services/category_service/overview.py",
        code_sha256=CODE_SHA["backend/services/category_service/overview.py"],
        anchors=["COUNT(DISTINCT user_id) AS total_users"],
        lines=["290"],
        note="人数分母基础存在，不等于目标 AUS 合同已落地或真实数据已对账。",
    ),
    _metric(
        id="metric.member_premium:code-overview-member-aov-over-store-line-avg",
        concept_id="concept.member_premium",
        layer="code_snapshot",
        name="旧概览会员每单 / 全店行均",
        formula="(member_amount / member_order_count) / avg_order_value",
        unit="unspecified_ratio",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D002"],
        textbook_refs=["tb.16.premium"],
        findings=["M02"],
        code_path="backend/services/metrics/overview.py",
        code_sha256=CODE_SHA["backend/services/metrics/overview.py"],
        anchors=["member_premium = member_avg_order_value / current['avg_order_value']"],
        lines=["285", "287"],
        note="注释称 AUS，比较对象与粒度均与 D002 不同。",
    ),
    _metric(
        id="metric.gsv:code-calculations-exclude-is-refund",
        concept_id="concept.gsv",
        layer="code_snapshot",
        name="semantic GSV 谓词排除全部 is_refund",
        formula="is_goujinjin = FALSE AND order_status != '交易关闭' AND is_refund = FALSE",
        unit="predicate",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D003"],
        findings=["M03"],
        code_path="backend/semantic/calculations.py",
        code_sha256=CODE_SHA["backend/semantic/calculations.py"],
        anchors=["GSV_PREDICATE"],
        lines=["39"],
    ),
    _metric(
        id="metric.gsv:code-competition-refunds-as-of",
        concept_id="concept.gsv",
        layer="code_snapshot",
        name="competition 带日期退款扣额",
        formula="refunds_as_of + iter_effective_orders; fallback to flag filter when no dated table",
        unit="money",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D003", "D006"],
        findings=["M03", "M04", "M10"],
        code_path="backend/services/metrics/competition_compute.py",
        code_sha256=CODE_SHA["backend/services/metrics/competition_compute.py"],
        anchors=["refunds_as_of", "iter_effective_orders"],
        lines=["117", "134"],
        note="有日期退款时扣金额；无日期表时回退标志过滤。不能静默回退冒充按实际退款净额。",
    ),
    _metric(
        id="metric.sample_roi:code-sampling-service",
        concept_id="concept.sample_window",
        layer="code_snapshot",
        name="旧派样 ROI 复购人数/金额",
        formula="get_sampling_roi repurchase users/amount; denominator all sample users in window",
        unit="mixed",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D009", "D010", "D011"],
        findings=["M18", "M19", "M20", "M21"],
        code_path="backend/services/sampling_service.py",
        code_sha256=CODE_SHA["backend/services/sampling_service.py"],
        anchors=["get_sampling_roi", "first_sample_received_at", "first_sample_time=MIN(pay_time)"],
        lines=["237", "289"],
        note="不含投入/毛利/对照。窗口含次日 00:00 边界。未按数据截止排除未成熟。",
    ),
    _metric(
        id="metric.ltv:code-specified-day-next-day",
        concept_id="concept.ltv",
        layer="code_snapshot",
        name="旧 LTV：指定日购买者次日起累计",
        formula="cohort = buyers on specified date; accumulate GSV from next day for 90/180/365",
        unit="money",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D012"],
        findings=["M24", "M12"],
        code_path="backend/services/lifetime_value_service.py",
        code_sha256=CODE_SHA["backend/services/lifetime_value_service.py"],
        anchors=["_cohort_user_ids", "_pct_change", "get_lifetime_value_summary"],
        lines=["63", "80", "121"],
        note="不是默认新客终身利润。channel 只筛 cohort。previous=0 时 _pct_change 返回 0。",
    ),
    _metric(
        id="metric.uv:code-sum-daily-visitors",
        concept_id="concept.uv",
        layer="code_snapshot",
        name="visitor_service SUM(visitors)",
        formula="SUM(visitors) and SUM(new_members) across days",
        unit="count",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D015"],
        findings=["M23"],
        code_path="backend/services/visitor_service.py",
        code_sha256=CODE_SHA["backend/services/visitor_service.py"],
        anchors=["SUM(visitors)", "get_visitor_summary"],
        lines=["24", "55"],
    ),
    _metric(
        id="metric.basket:code-order-support",
        concept_id="concept.basket",
        layer="code_snapshot",
        name="购物篮订单级 support/confidence/lift",
        formula="distinct order_id associations",
        unit="raw_ratio_0_1",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D008"],
        findings=["M15"],
        code_path="backend/services/category_service/basket.py",
        code_sha256=CODE_SHA["backend/services/category_service/basket.py"],
        anchors=["_compute_market_basket"],
        lines=["54"],
        note="不能直接冒充教材人数连带率。",
    ),
    _metric(
        id="metric.product_repurchase:code-standard-hist-join",
        concept_id="concept.product_repurchase",
        layer="code_snapshot",
        name="品类 standard 回购历史集合 JOIN",
        formula="historical cohort LEFT JOIN repurchase buyers",
        unit="raw_ratio_0_1",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D008"],
        findings=["M17"],
        code_path="backend/services/category_service/repurchase/standard.py",
        code_sha256=CODE_SHA["backend/services/category_service/repurchase/standard.py"],
        anchors=["_run_category_repurchase_period"],
        lines=["30"],
        note="已有历史集合限制，不能误报所有代码都错。仍不是已验证的 crm-metrics/v1 能力。",
    ),
    _metric(
        id="metric.yoy:code-or-zero",
        concept_id="concept.yoy",
        layer="code_snapshot",
        name="同比 None 被 or 0",
        formula="yoy_absolute returns None when denominator invalid; overview uses or 0",
        unit="raw_ratio_or_zero",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D018", "D017"],
        findings=["M11", "M12"],
        code_path="backend/services/metrics/overview.py",
        code_sha256=CODE_SHA["backend/services/metrics/overview.py"],
        anchors=["yoy_absolute(...) or 0"],
        lines=["301", "316"],
    ),
    _metric(
        id="metric.rfm:code-thresholds-v1",
        concept_id="concept.rfm",
        layer="code_snapshot",
        name="segments.py 固定 RFM 阈值",
        formula="R=[30,90,180,365] days; F=[1,2,3,4]; M=[100,300,500,1000]",
        unit="threshold_table",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D016"],
        findings=["M26"],
        code_path="backend/semantic/segments.py",
        code_sha256=CODE_SHA["backend/semantic/segments.py"],
        anchors=["RFM_THRESHOLDS"],
        lines=["22"],
        rfm_threshold_version=RFM_THRESHOLD_VERSION,
    ),
    _metric(
        id="metric.contract.member_premium-field",
        concept_id="concept.member_premium",
        layer="code_snapshot",
        name="旧合同 member_premium 字段说明",
        formula="OverviewMetrics.member_premium description: 会员溢价 %（会员AUS/全店AUS）",
        unit="percent_in_description_but_service_emits_ratio",
        definition_review_status="code_snapshot_only",
        implementation_status="code_snapshot",
        decision_ids=["D002", "D017"],
        findings=["M02", "M12"],
        code_path="backend/contracts/metrics.py",
        code_sha256=CODE_SHA["backend/contracts/metrics.py"],
        anchors=["member_premium"],
        lines=["34"],
    ),
]

assert not any(m["implementation_status"] in {"implemented", "real_reconciled", "synthetic_verified"} for m in TARGET_METRICS)
assert all(m["layer"] == "code_snapshot" for m in CODE_SNAPSHOT_METRICS)
assert all(m["layer"] == "target_definition" for m in TARGET_METRICS)
VERIFIED_IMPLEMENTATIONS: list[dict] = []
