#!/usr/bin/env python3
"""Generate this isolated API's OpenAPI and SDK schemas without starting CRM."""
from pathlib import Path
import json
import os
import sys

# Offline schema generation never loads local accounts or dotenv credentials.
os.environ["PYTHON_DOTENV_DISABLED"] = "1"
os.environ["FQ_CRM_PASSWORDS"] = "schema:synthetic-schema-only"
os.environ["FQ_CRM_ADMINS"] = "schema"

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from backend.crm_metrics_app import create_crm_metrics_app  # noqa: E402
from backend.contracts.crm_metrics_v1 import MetricRequest, MetricResult  # noqa: E402


def project(node, defs):
    if "$ref" in node:
        return project(defs[node["$ref"].split("/")[-1]], defs)
    if "anyOf" in node:
        return {"oneOf": [project(item, defs) for item in node["anyOf"]]}
    result = {key: value for key, value in node.items() if key in ("type", "const", "enum", "description")}
    if result.get("type") == "object":
        result["additionalProperties"] = node.get("additionalProperties", True)
        result["properties"] = {key: {**project(value, defs), **({"required": True} if key in node.get("required", []) else {})} for key, value in node.get("properties", {}).items()}
    elif result.get("type") == "array":
        result["items"] = project(node["items"], defs)
    return result or {"type": "json"}


def dashboard_openapi():
    from fastapi import FastAPI
    from backend.routers.metrics import router
    app = FastAPI(title="CRM dashboard purchase aggregates", version="1")
    app.include_router(router)
    schema = app.openapi()
    allowed = {
        "/api/v1/metrics/dashboard-purchases",
        "/api/v1/metrics/dashboard-readiness",
        "/api/v1/metrics/dashboard-membership",
        "/api/v1/metrics/dashboard-net-gsv",
    }
    schema["paths"] = {key: value for key, value in schema["paths"].items()
                       if key in allowed or key.startswith(("/api/v1/metrics/dashboard-snapshots", "/api/v1/metrics/crm-"))}
    used = set()

    def visit(node):
        if isinstance(node, dict):
            ref = node.get("$ref", "")
            if ref.startswith("#/components/schemas/"):
                name = ref.rsplit("/", 1)[1]
                if name not in used:
                    used.add(name)
                    visit(schema["components"]["schemas"][name])
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for value in node:
                visit(value)

    visit(schema["paths"])
    schema["components"]["schemas"] = {name: schema["components"]["schemas"][name] for name in sorted(used)}
    return schema


def main():
    query = MetricRequest.model_json_schema()
    output = MetricResult.model_json_schema()
    request_schema = project(query, query.get("$defs", {}))
    request_schema["properties"]["source_id"]["const"] = "synthetic-crm-metrics"
    request_schema["properties"]["contains_real_data"]["const"] = False
    schemas = {"request": request_schema, "output": project(output, output.get("$defs", {}))}
    outputs = {
        "backend/contracts/crm-dashboard.openapi.json": json.dumps(dashboard_openapi(), ensure_ascii=False, indent=2) + "\n",
        "backend/contracts/crm-metrics.openapi.json": json.dumps(create_crm_metrics_app().openapi(), ensure_ascii=False, indent=2) + "\n",
        "dsh-plugins/crm-knowledge/src/contract.generated.ts": "// Generated by scripts/crm-calibration/generate_contract.py; do not edit.\nexport const schemas = " + json.dumps(schemas, ensure_ascii=False, indent=2) + " as const;\n",
    }
    for rel, text in outputs.items():
        dest = ROOT / rel
        if "--check" in sys.argv:
            assert dest.read_text() == text, f"contract drift: {rel}"
        else:
            dest.write_text(text)


if __name__ == "__main__":
    main()
